version: "3.8"
services:
    php8:
        image: leoqbc/php:8.0.7-cli
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - 80:80
        command: php -S 0.0.0.0:80 -t public/
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3307:3306
        environment: 
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: valle